version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - main
  django:
    build: .
    command: uvicorn --app-dir /code/django config.asgi:application --host 0.0.0.0 --port 8001 --lifespan=off --reload-dir /code/django --reload
    #command: gunicorn --pythonpath '/code/django' config.wsgi:application -w 4 -b :8001 --reload
    #command: gunicorn --pythonpath '/code/django' config.asgi:application -w 4 -b :8001 -k uvicorn.workers.UvicornWorker --reload
    volumes:
      - ./django:/code/django/
    networks:
      - main
    tty: true
    depends_on:
      - postgres
  nginx:
    image: nginx:1.21-alpine
    env_file: ./nginx.env
    volumes:
      - ./django/static:/usr/share/nginx/django/static
      - ./django/resources:/usr/share/nginx/django/resources
      - ./${NGINX_CONF}:/etc/nginx/templates
      - ${LOCAL_CERTS_PATH}:${NGINX_CERTS_PATH}
    ports:
      - 8000:80
      - 8443:443
    networks:
      - main
    depends_on:
      - django

volumes:
  pgdata:

networks:
  main: